// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5uvuptOXLMV-QprrzeMr7aF6rSPdz4Vw',
    appId: '1:823329913234:web:342d55c1827f42af29694b',
    messagingSenderId: '823329913234',
    projectId: 'taskapp-dba14',
    authDomain: 'taskapp-dba14.firebaseapp.com',
    storageBucket: 'taskapp-dba14.appspot.com',
    measurementId: 'G-0X0FYZTTT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_sfGm7S-_DUYjfaiRRdgqS7m6pv9dvNE',
    appId: '1:823329913234:android:7fafefc2cce9b84029694b',
    messagingSenderId: '823329913234',
    projectId: 'taskapp-dba14',
    storageBucket: 'taskapp-dba14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOz-s2hyoD4amQ5mCgl3Z2pVs4cnYjN0Y',
    appId: '1:823329913234:ios:df83205475dd9fb629694b',
    messagingSenderId: '823329913234',
    projectId: 'taskapp-dba14',
    storageBucket: 'taskapp-dba14.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOz-s2hyoD4amQ5mCgl3Z2pVs4cnYjN0Y',
    appId: '1:823329913234:ios:2fbb9a31e70b5ac129694b',
    messagingSenderId: '823329913234',
    projectId: 'taskapp-dba14',
    storageBucket: 'taskapp-dba14.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
